on:
  schedule:
    # 相关语法 https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07 would run a command on the first and fifteenth of each month
    - cron: '0 2 1,8,15,22 * *'

jobs:
  test_schedule:
    if: github.repository == 'Tencent/tdesign'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.9
      - name: Install Dependencies
        run: pnpm install
      - name: run auto release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run auto-release
