name: Copy to Repos

on:
  workflow_dispatch:

jobs:
  call-preview-1:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-vue
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-2:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-vue-next
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-3:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-react
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-4:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-miniprogram
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-5:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-common
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-6:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-starter-cli
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-7:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-vue-starter
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-8:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-vue-next-starter
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  call-preview-9:
    uses: Tencent/tdesign/.github/workflows/file-copy.yml@main
    with:
      repo: tdesign-icons
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}